import { logger } from '@/shared/logger/logger'
import type { BackupHistoryItem } from '../../types/backup'

export interface BackupFileInfo {
  fileName: string
  filePath: string
  timestampStr: string
  originalName: string
}

export class BackupRetention {
  // New V2.4 Pattern: {baseName}_WPS排版备份_{yyyyMMdd_HHmmss}.{ext}
  private static readonly BACKUP_NAME_REGEX_V2 = /^(.+)_WPS排版备份_(\d{8}_\d{6})\.([a-zA-Z0-9]+)$/
  // Backward compatible V2.4-early Pattern: yyyyMMdd_HHmmss_originalName.ext
  private static readonly BACKUP_NAME_REGEX_V1 = /^(\d{8}_\d{6})_(.+)$/

  /**
   * Check if a filename is generated by Word Formatter BackupService
   */
  static isWordFormatterBackup(fileName: string): boolean {
    return this.BACKUP_NAME_REGEX_V2.test(fileName) || this.BACKUP_NAME_REGEX_V1.test(fileName)
  }

  /**
   * Parse backup metadata from filename
   */
  static parseBackupFileName(fileName: string, fullPath: string): BackupFileInfo | null {
    const matchV2 = fileName.match(this.BACKUP_NAME_REGEX_V2)
    if (matchV2) {
      return {
        fileName,
        filePath: fullPath,
        timestampStr: matchV2[2],
        originalName: `${matchV2[1]}.${matchV2[3]}`
      }
    }

    const matchV1 = fileName.match(this.BACKUP_NAME_REGEX_V1)
    if (matchV1) {
      return {
        fileName,
        filePath: fullPath,
        timestampStr: matchV1[1],
        originalName: matchV1[2]
      }
    }

    return null
  }

  /**
   * Prune older backups for a specific document from backup_history.json
   * STRICT SAFETY: ONLY deletes files explicitly tracked in backup history and confirmed to exist.
   *
   * @param historyItems List of items from backup_history.json
   * @param sourcePath Full path of the active document
   * @param retentionCount Max allowed backups to keep (default: 10)
   * @param deleteCallback Callback to actually delete the file (e.g. fs.removeFile)
   * @returns Updated history list and deleted paths
   */
  static pruneHistory(
    historyItems: BackupHistoryItem[],
    sourcePath: string,
    retentionCount: number = 10,
    deleteCallback: (filePath: string) => boolean | Promise<boolean>
  ): { updatedHistory: BackupHistoryItem[]; deletedFiles: string[] } {
    if (retentionCount <= 0) retentionCount = 10

    const cleanSource = sourcePath.replace(/\//g, '\\').toLowerCase()
    const matching: BackupHistoryItem[] = []
    const others: BackupHistoryItem[] = []

    for (const item of historyItems) {
      if (item.sourcePath.replace(/\//g, '\\').toLowerCase() === cleanSource) {
        matching.push(item)
      } else {
        others.push(item)
      }
    }

    // Sort matching descending by createdAt (newest first)
    matching.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())

    const deletedFiles: string[] = []
    const keptMatching: BackupHistoryItem[] = []

    for (let i = 0; i < matching.length; i++) {
      const item = matching[i]
      if (i < retentionCount) {
        keptMatching.push(item)
      } else {
        try {
          deleteCallback(item.backupPath)
          deletedFiles.push(item.backupPath)
          logger.info('BackupRetention', `Pruned excess backup from disk & history: ${item.backupPath}`)
        } catch (e) {
          logger.warn('BackupRetention', `Failed to delete pruned backup: ${item.backupPath}`, e)
        }
      }
    }

    return {
      updatedHistory: [...keptMatching, ...others],
      deletedFiles
    }
  }

  /**
   * Legacy / direct files array prune helper
   */
  static prune(
    files: { name: string; fullPath: string }[],
    retentionCount: number = 10,
    deleteCallback: (filePath: string) => boolean | Promise<boolean>,
    targetOriginalName?: string
  ): { deletedFiles: string[]; keptCount: number } {
    if (retentionCount <= 0) retentionCount = 10

    const validBackups: BackupFileInfo[] = []
    for (const f of files) {
      const parsed = this.parseBackupFileName(f.name, f.fullPath)
      if (parsed) {
        if (!targetOriginalName || parsed.originalName === targetOriginalName) {
          validBackups.push(parsed)
        }
      }
    }

    validBackups.sort((a, b) => b.timestampStr.localeCompare(a.timestampStr))

    const deletedFiles: string[] = []
    if (validBackups.length > retentionCount) {
      const toDelete = validBackups.slice(retentionCount)
      for (const item of toDelete) {
        try {
          const res = deleteCallback(item.filePath)
          if (res !== false) {
            deletedFiles.push(item.filePath)
          }
        } catch {}
      }
    }

    const keptCount = validBackups.length - deletedFiles.length
    return { deletedFiles, keptCount }
  }
}
